---
- include: apt_package.yml
  when: ansible_os_family == 'Debian'

- name: Copy munin-node.conf in the munin folder
  template: >
    src=munin-node.conf.j2
    dest=/etc/munin/munin-node.conf
    owner=munin
    group=munin
  notify:
    - restart munin-node
