---
#Task file for installing MariaDB on apt based distros

- name: Install MariaDB repository
  apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu trusty main' state=present

- name: Add repository key to the system
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- name: Install MariaDB via apt
  apt: pkg={{ item }} update_cache=yes
  with_items: 
    - mariadb-client
    - mariadb-server
    - python-mysqldb

#Adding MariaDB configuration
- name: Create MariaDB configuration file Debian/Ubuntu
  template : src=myDebian.cnf.j2 dest=/etc/mysql/my.cnf 
  notify: restart mysql
 
- name: Copy .my.cnf to the root home directory
  template : src=myDebian.cnf.j2 dest=/root/.my.cnf 
  notify: restart mysql

- name: Start MariaDB service 
  service : name=mysql state=started enabled=yes 

