---
- name: Create the Drupal database
  mysql_db:
    name: "{{ drupal_db_name }}"
    state: "present"

- name: Create the Drupal user
  mysql_user:
    name: "{{ drupal_db_user }}"
    password: "{{ drupal_db_password }}"
    host: "192.168.35.0/255.255.255.0"
    state: "present"
    priv: "{{ drupal_db_name }}.*: ALL"
