---
- name: Create the Icinga database
  mysql_db:
    name: "{{ icinga2_db_name }}"
    state: "present"

- name: Create the Icinga user
  mysql_user:
    name: "{{ icinga2_db_user }}"
    password: "{{ icinga2_db_password }}"
    host: "192.168.35.0/255.255.255.0"
    state: "present"
    priv: "{{ icinga2_db_name }}.*: ALL"
