---
#Install and start MariaDB
- include: apt_package.yml
  when: ansible_os_family == 'Debian'
- include: yum_package.yml
  when: ansible_os_family == 'RedHat'

#Root password
- name: Change the root password
  mysql_user: user=root
              host={{ item }} 
              password={{ mysql_root_password }}
              login_user=root
              login_password={{ mysql_root_password }}
              check_implicit_admin=yes
              priv="*.*:ALL, GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

#Adding MariaDB configuration
- name: Create MariaDB configuration file RedHat/CentOS
  template : src=myRedhat.cnf.j2 dest=/etc/my.cnf
  notify: restart mariadb
  when: ansible_os_family == 'RedHat'

- name: Copy .my.cnf to the root home directory
  copy: src=/etc/my.cnf dest=/root/.my.cnf
  when: ansible_os_family == 'RedHat'

#Delete the useless code
- name: Delete the anonymous sql server user
  mysql_user: user=""
              state=absent

- name: Remove the MariaDB test database
  mysql_db: name=test
            state=absent

#Fedora-Commons configuration
- include: fedora.yml
