---
- name: Create the ojs database
  mysql_db:
    name: "{{ ojs_db_name }}"
    state: "present"

- name: Create the ojs user
  mysql_user:
    name: "{{ ojs_db_user }}"
    password: "{{ ojs_db_password }}"
    host: "192.168.35.0/255.255.255.0"
    state: "present"
    priv: "{{ ojs_db_name }}.*: ALL"
