---
- name: Install Tomcat via yum
  yum: >
    name={{item}}
  with_items:
    - tomcat
    - tomcat-webapps
    - tomcat-admin-webapps

- name: Start tomcat
  service: >
    name=tomcat
    state=started
    enabled=yes
