---
- include: apt_package.yml
  when: ansible_os_family == 'Debian'

- include_vars: redmine_pass.yml

- name: Copy configuration file for mail
  template: >
    src=configuration.yml.j2
    dest=/etc/redmine/default/configuration.yml

- name: Copy configuration file for database
  template: >
    src=database.yml.j2
    dest=/etc/redmine/default/database.yml

- name: Copy configuration file for redmine
  template: >
    src=default.conf.j2
    dest=/etc/apache2/sites-enabled/default.conf
  notify:
    - restart apache2

- name: Copy configuration file for mod-passenger
  template: >
    src=passenger.conf.j2
    dest=/etc/apache2/mods-available/passenger.conf

- name: Enable module
  apache2_module: >
    name=passenger
    state=present

- name: Create link to web directory folder for redmine
  file: >
    src=/usr/share/redmine/public
    dest=/var/www/redmine
    state=link

- name: Change ownership of the redmine folder
  file: >
    path=/var/www/redmine/
    owner=www-data
    group=www-data
    recurse=yes
    state=directory

# - name: Create symbolic link to the plugin directory
#   file: >
#     src=/usr/share/redmine/public/
#     dest=/var/cache/redmine/default/plugin_assets/public
#     state=link
#   notify:
#     - restart apache2
