---
- include: apt_package.yml
  when: ansible_os_family == 'Debian'

- include_vars: redmine_pass.yml

- name: Copy configuration file for mail
  template: >
    src=configuration.yml.j2
    dest=/etc/redmine/default/configuration.yml

- name: Copy configuration file for database
  template: >
    src=database.yml.j2
    dest=/etc/redmine/default/database.yml

- name: Copy configuration file for redmine
  template: >
    src=redmine.conf.j2
    dest=/etc/apache2/sites-available/redmine.conf

- name: Enable site
  command: a2ensite redmine.conf

- name: Copy configuration file for mod-passenger
  template: >
    src=passenger.conf.j2
    dest=/etc/apache2/mods-available/passenger.conf

- name: Enable module
  apache2_module: >
    name=passenger
    state=present

- name: Create link to web directory folder for redmine
  file: >
    src=/usr/share/redmine/public
    dest=/var/www/redmine
    state=link
  file: >
    src=/usr/share/redmine/public
    dest=/var/cache/redmine/default/plugin_assets
    state=link
  notify:
    - restart apache2
