---
- name: Install Apache via apt
  apt:
    name: apache2
    state: present
  notify:
    - start apache2

- meta: flush_handlers

- name: Copy default configuration
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - restart apache2
