---
- include: yum_package.yml
  when: ansible_os_family ==  'RedHat'
- include: apt_package.yml
  when: ansible_os_family ==  'Debian'
- include_vars: fedora_pass.yml

- name: Download Fedora-Commons source
  get_url:
    url: http://sourceforge.net/projects/fedora-commons/files/fedora/{{ fedora_version }}/fcrepo-installer-{{ fedora_version }}.jar
    dest: "{{ download_dir }}/fcrepo-installer-{{ fedora_version }}.jar"
  when: ansible_os_family ==  "Debian"

- name: Download Fedora-Commons source
  get_url:
    url: http://sourceforge.net/projects/fedora-commons/files/fedora/{{ fedora_version }}/fcrepo-installer-{{ fedora_version }}.jar
    dest: /home/vagrant/sync/downloads/fcrepo-installer-{{ fedora_version }}.jar
  when: ansible_os_family ==  'RedHat'

- name: Copy install.properties
  template:
    src: install.propertiesRedHat.j2
    dest: /tmp/install.properties
  when: ansible_os_family ==  'RedHat'

- name: Copy install.properties
  template:
    src: install.propertiesDebian.j2
    dest: /tmp/install.properties
  when: ansible_os_family ==  "Debian"

- name: Install Fedora-Commons
  command: /usr/bin/java -jar /home/vagrant/sync/downloads/fcrepo-installer-{{ fedora_version }}.jar /tmp/install.properties
  args:
    creates: /usr/share/tomcat/fedora
  when: ansible_os_family ==  'RedHat'

- name: Install Fedora-Commons
  command: /usr/bin/java -jar {{ download_dir }}/fcrepo-installer-{{ fedora_version }}.jar /tmp/install.properties
  args:
    creates: /var/lib/tomcat7/fedora
  when: ansible_os_family ==  "Debian"

- name: change fedora ownership debian
  file:
    path: /var/lib/tomcat7
    owner: tomcat7
    group: tomcat7
    state: directory
    recurse: yes
  when: ansible_os_family == 'Debian'
  notify:
    - restart tomcat7

- name: change fedora ownership Redhat
  file:
    path: /var/lib/tomcat
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes
  when: ansible_os_family == 'RedHat'
  notify:
    - restart tomcat

- meta: flush_handlers

- name: Wait until the webapps are installed Redhat
  wait_for:
    path: /var/lib/tomcat/webapps/fedora/WEB-INF
  when: ansible_os_family ==  'RedHat'

- name: Wait until the webapps are installed Debian
  wait_for:
    path: /var/lib/tomcat7/webapps/fedora/WEB-INF
  when: ansible_os_family ==  "Debian"

- name: Copy web.xml in the fedora-commons folder
  template:
    src: webRedhat.xml.j2
    dest: /var/lib/tomcat/webapps/fedora/WEB-INF/web.xml
  notify:
    - change fedora ownership redhat
    - change tomcat ownership redhat
    - restart tomcat
  when: ansible_os_family ==  'RedHat'

- name: Copy web.xml in the fedora-commons folder
  template:
    src: webDebian.xml.j2
    dest: /var/lib/tomcat7/webapps/fedora/WEB-INF/web.xml
  notify:
    - change fedora ownership debian
    - change tomcat ownership debian
    - restart tomcat7
  when: ansible_os_family ==  "Debian"
