---
- name: Bootstrap distribution with ansible prerequisite
  script: >
    scripts/bootstrap_ansible_apt.sh creates=/usr/bin/python

- name: Install useful package Debian
  apt: >
    pkg={{ item }}
    update_cache=yes
  with_items:
    - vim
    - bash-completion
    - iputils-ping
    - bind9-host
    - tcpdump
    - git
    - apt-transport-https
    - sudo
    - cron
