---
- name: Install useful package Debian
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - vim
    - bash-completion
    - iputils-ping
    - bind9-host
    - tcpdump
    - git
    - apt-transport-https
