---
- name: Install useful package Debian
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
    - vim
    - bash-completion
    - iputils-ping
    - bind9-host
    - tcpdump
    - git
    - apt-transport-https
    - sudo
    - cron
    - python-keyczar
    - python-selinux
