---
- include: yum_package.yml
  when: ansible_os_family == 'RedHat'
- include: apt_package.yml
  when: ansible_os_family == 'Debian'

- name: Create downloads directory
  file: path=/vagrant/downloads/ state=directory
