---
- include: yum_package.yml
  when: ansible_os_family ==  'RedHat'
- include: apt_package.yml
  when: ansible_os_family ==  'Debian'

- name: Create downloads directory
  file:
    path: "{{ download_dir }}"
    state: directory

- name: Setup locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_CA.UTF-8
    - en_US.UTF-8
    - fr_CA.UTF-8
    - fr_FR.UTF-8

- name: Copy .bashrc in the root user home folder
  template:
    src: .bashrc.j2
    dest: /root/.bashrc

#### Vagrant Only ####
- name: Copy .bashrc in the vagrant user home folder
  template:
    src: .bashrc.j2
    dest: /home/vagrant/.bashrc
