---
- name: start httpd
  service: >
    name=httpd
    state=started
    enabled=yes

- name: restart httpd
  service: >
    name=httpd
    state=restarted
    enabled=yes

- name: start apache2
  service: >
    name=apache2
    state=started
    enabled=yes

- name: restart apache2
  service: >
    name=apache2
    state=restarted
    enabled=yes
