- include: apt_package.yml
  when: ansible_os_family ==  'Debian'

- name: Create /var/cache/bind/erudit/ folder
  file:
    path: /var/cache/bind/erudit/
    state: directory

- name: Copy zones configuration files for erudit.org
  template:
    src: erudit.org.j2
    dest: /var/cache/bind/erudit/erudit.org
  notify:
    - re-read zone files

- name: Copy BIND9 configuration files Master
  template:
    src: namedMaster.conf.local.j2
    dest: /etc/bind/named.conf.local
  when: bind_master

- name: Copy BIND9 configuration files Slave
  template:
    src: namedSlave.conf.local.j2
    dest: /etc/bind/named.conf.local
  when: not bind_master

- name: Copy BIND9 configuration files
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
