---
- name: Install Bind
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - bind
    - bind-utils

- name: Create /var/cache/bind/erudit/ folder
  file:
    path: /var/cache/bind/erudit/
    state: directory

- name: Copy zones configuration files for erudit.org
  template:
    src: erudit.org.j2
    dest: /var/cache/bind/erudit/erudit.org
  notify:
    - re-read zone files

- name: Copy BIND9 configuration files Master
  template:
    src: namedMaster.conf.local.j2
    dest: /etc/named.conf.local
  when: bind_master

- name: Copy BIND9 configuration files Slave
  template:
    src: namedSlave.conf.local.j2
    dest: /etc/named.conf.local
  when: not bind_master

- name: Copy BIND9 configuration files
  template:
    src: named.conf.options.j2
    dest: /etc/named.conf.options
