---
- name: Install php and dependencies for WordPress
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-mysql
    - php5-xmlrpc

- name: Copy php.ini
  template:
    src: php.ini.j2
    dest: /etc/php5/cli/php.ini
