---
wordpress_version: 4.3.1

#WordPress configuration
wordpress_db_name: wordpress
wordpress_db_user: wordpress
# Vagrant configuration only
wordpress_db_host: "{{ hostvars[groups['mariadb'][0]]['ansible_eth1']['ipv4']['address'] }}"
# Server configuration
#wordpress_db_host: "{{ hostvars[groups['mariadb'][0]]['ansible_default_ipv4']['address']}}"
