---
- include: apt_package.yml
  when: ansible_os_family == 'Debian'

- name: Copy config-solr.xml
  template:
    src: config-solr.xml.j2
    dest: /etc/metaproxy/metaproxy.xml
  notify:
    - restart metaproxy
