---
- include_vars: icinga_pass.yml

- name: Add Icinga repository key
  apt_key:
    url: http://packages.icinga.org/icinga.key
    state: present

- name: Add Icinga repository
  apt_repository:
    repo: "deb http://packages.icinga.org/debian icinga-jessie main"
    state: present

- name: Add Icinga repository
  apt_repository:
    repo: "deb-src http://packages.icinga.org/debian icinga-jessie main"
    state: present

- name: Install icinga
  apt:
    name: icinga2
    update_cache: yes
    state: present
