---
- include: apt_package.yml
  when: ansible_os_family == 'Debian'
- include: yum_package.yml
  when: ansible_os_family == 'RedHat'
  
- include_vars: icinga2_pass.yml

- name: Enable icinga2 feature command
  command: icinga2 feature enable command
  args:
    creates: /etc/icinga2/features-enabled/command.conf
  notify:
    - restart icinga2

- name: Enable icinga2 feature ido-mysql
  command: icinga2 feature enable ido-mysql
  args:
    creates: /etc/icinga2/features-enabled/ido-mysql.conf
  notify:
    - restart icinga2

- name: Copy ido-mysql.conf file
  template:
    src: ido-mysql.conf.j2
    dest: /etc/icinga2/features-enabled/ido-mysql.conf
  notify:
    - restart icinga2
