---
- include: yum_package.yml
  when: ansible_os_family ==  'RedHat'
- include: apt_package.yml
  when: ansible_os_family ==  'Debian'

- name: Copy default configuration file Debian
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
  when: ansible_os_family == 'Debian'

- name: Copy default configuration file RedHat
  template:
    src: nginxRedhat.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  when: ansible_os_family == 'RedHat'

- name: Start Nginx
  service:
     name: nginx
     enabled: yes
     state: started
