---
- include: yum_package.yml
  when: ansible_os_family == 'CentOS'
- include: apt_package.yml
  when: ansible_os_family == 'Debian'

- name: Start Nginx
  service: name=nginx enabled=yes state=started
