---
- name: Add Icinga repository key
  rpm_key:
    key: http://packages.icinga.org/icinga.key
    state: present

- name: Add Icinga repository
  yum:
    name: "http://packages.icinga.org/epel/7/release/noarch/icinga-rpm-release-7-1.el7.centos.noarch.rpm"
    state: present

- name: Install Icinga-web package
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - icingaweb2
    - icingaweb2-common
