---
- name: Install Apache
  hosts: apache
  sudo: yes

  roles:
    - common
    - monitoring
    - {role: bind, bind_master: false }
    - apache
    - {role: php, phpini_folder: /etc/php5/apache2/php.ini }
