---
- name: Create dspace database
  become_user: postgres
  postgresql_db:
    name: "{{ dspace_db_name }}"
    encoding: "UTF-8"
    state: present

- name: Create dspace user
  become_user: postgres
  postgresql_user:
    name: "{{ dspace_db_user }}"
    password: "{{ dspace_db_password }}"
    db: "{{ dspace_db_name }}"
    state: present
    priv: ALL
    role_attr_flags: CREATEDB

- name: copy dspace.sql
  copy:
    src: dspaceTEST.sql
    dest: /tmp/dspaceTEST.sql
    mode: "ugo=rwx"

- name: Install database
  command: "psql -U {{ dspace_db_user }} -f /tmp/dspaceTEST.sql -d {{ dspace_db_name }} -h localhost"
  environment:
    PGPASSWORD: "{{ dspace_db_password }}"
