---
  - include: apt_package.yml
    when: ansible_os_family == "Debian"
  - include: yum_package.yml
    when: ansible_os_family == "RedHat"

  - name: Start postgresql
    service: name=postgresql state=started enabled=yes
