---
- include: apt_package.yml
  when: ansible_os_family ==  "Debian"
- include: yum_package.yml
  when: ansible_os_family ==  'RedHat'
  
- include_vars: postgresql_pass.yml

#Odoo configuration
- include: odoo.yml
#Dspace configuration
- include: dspace.yml
