---
- name: Create odoo user
  become_user: postgres
  postgresql_user:
    name: "{{ odoo_db_user }}"
    password: "{{ odoo_db_password }}"
    state: present
    role_attr_flags: CREATEDB,SUPERUSER
