---
- include: apt_package.yml
  when: ansible_os_family == "Debian"
- include: yum_package.yml
  when: ansible_os_family == 'CentOS'

#- name: Configure and start gitlab
#  command: sudo gitlab-ctl reconfigure
